/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	G:/project_development/risc-v/tree_core_cpu/fpga/bare_metal/source/al_ip/ram.v
 ** Date	:	2021 03 31
 ** TD version	:	5.0.25878
\************************************************************/

`timescale 1ns / 1ps

module ram ( doa, dia, addra, cea, ocea, clka, wea, rsta );


	parameter DATA_WIDTH_A = 2; 
	parameter ADDR_WIDTH_A = 8;
	parameter DATA_DEPTH_A = 256;
	parameter DATA_WIDTH_B = 2;
	parameter ADDR_WIDTH_B = 8;
	parameter DATA_DEPTH_B = 256;
	parameter REGMODE_A    = "OUTREG";
	parameter WRITEMODE_A  = "NORMAL";

	output [DATA_WIDTH_A-1:0] doa;

	input  [DATA_WIDTH_A-1:0] dia;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  wea;
	input  cea;
	input  ocea;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.MODE("SP"),
				.REGMODE_A(REGMODE_A),
				.WRITEMODE_A(WRITEMODE_A),
				.RESETMODE("SYNC"),
				.IMPLEMENT("32K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("NONE"),
				.FILL_ALL("00"))
			inst(
				.dia(dia),
				.dib({2{1'b0}}),
				.addra(addra),
				.addrb({8{1'b0}}),
				.cea(cea),
				.ceb(1'b0),
				.ocea(ocea),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule