/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	G:/project_development/risc-v/tree_core_cpu/fpga/bare_metal/source/al_ip/rom.v
 ** Date	:	2021 03 31
 ** TD version	:	5.0.25878
\************************************************************/

`timescale 1ns / 1ps

module rom ( doa, addra, clka, rsta );

	output [1:0] doa;

	input  [7:0] addra;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(2),
				.ADDR_WIDTH_A(8),
				.DATA_DEPTH_A(256),
				.DATA_WIDTH_B(2),
				.ADDR_WIDTH_B(8),
				.DATA_DEPTH_B(256),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.IMPLEMENT("32K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../../data/multi_led_blink.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({2{1'b0}}),
				.dib({2{1'b0}}),
				.addra(addra),
				.addrb({8{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule