package treecorel2

import chisel3._
import chisel3.util._

class ISAIO extends Bundle {
  val ADD        = Bool()
  val ADDI       = Bool()
  val ADDW       = Bool()
  val ADDIW      = Bool()
  val SUB        = Bool()
  val SUBW       = Bool()
  val LUI        = Bool()
  val AUIPC      = Bool()
  val XOR        = Bool()
  val XORI       = Bool()
  val OR         = Bool()
  val ORI        = Bool()
  val AND        = Bool()
  val ANDI       = Bool()
  val SLL        = Bool()
  val SLLI       = Bool()
  val SLLW       = Bool()
  val SLLIW      = Bool()
  val SRL        = Bool()
  val SRLI       = Bool()
  val SRLW       = Bool()
  val SRLIW      = Bool()
  val SRA        = Bool()
  val SRAI       = Bool()
  val SRAW       = Bool()
  val SRAIW      = Bool()
  val SLT        = Bool()
  val SLTI       = Bool()
  val SLTU       = Bool()
  val SLTIU      = Bool()
  val BEQ        = Bool()
  val BNE        = Bool()
  val BLT        = Bool()
  val BGE        = Bool()
  val BLTU       = Bool()
  val BGEU       = Bool()
  val JAL        = Bool()
  val JALR       = Bool()
  val FENCE      = Bool()
  val FENCE_I    = Bool()
  val ECALL      = Bool()
  val EBREAK     = Bool()
  val CSRRW      = Bool()
  val CSRRS      = Bool()
  val CSRRC      = Bool()
  val CSRRWI     = Bool()
  val CSRRSI     = Bool()
  val CSRRCI     = Bool()
  val LD         = Bool()
  val LW         = Bool()
  val LH         = Bool()
  val LB         = Bool()
  val LWU        = Bool()
  val LHU        = Bool()
  val LBU        = Bool()
  val SD         = Bool()
  val SW         = Bool()
  val SH         = Bool()
  val SB         = Bool()
  val MRET       = Bool()
  val SRET       = Bool()
  val WFI        = Bool()
  val SFENCE_VMA = Bool()
}
